### ISSUE TITLE
官方demo在andriod4.4版本机型报错

### ISSUE THREAD

**Issue by wittech** [qunarcorp/imsdk-android#59]
09-03 12:37:58.989 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err: android.database.sqlite.SQLiteException: unrecognized token: "0x01" (Sqlite code 1): , while compiling: SELECT a.'From', GROUP_CONCAT(a.MsgId) as msgIdList  FROM IM_Message as a WHERE (0x01 & a.ReadedTag)<>0x01 and a.'From' <> ? GROUP By a.'From';, (OS error - 2:No such file or directory)
09-03 12:37:59.009 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err:     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
09-03 12:37:59.009 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err:     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
09-03 12:37:59.009 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err:     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
09-03 12:37:59.019 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err:     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
09-03 12:37:59.019 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err:     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
09-03 12:37:59.019 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err:     at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
09-03 12:37:59.029 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err:     at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
09-03 12:37:59.029 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err:     at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
09-03 12:37:59.029 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err:     at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1253)
09-03 12:37:59.029 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err:     at com.qunar.im.core.manager.IMDatabaseManager.getMessageStateSendNotXmppIdJson(IMDatabaseManager.java:6188)
09-03 12:37:59.029 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err:     at com.qunar.im.core.manager.LoginComplateManager.updateMessageStateNoticeServer(LoginComplateManager.java:292)
09-03 12:37:59.039 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err:     at com.qunar.im.core.manager.LoginComplateManager.loginComplate(LoginComplateManager.java:115)
09-03 12:37:59.039 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err:     at com.qunar.im.core.manager.IMLogicManager$7.run(IMLogicManager.java:1702)
09-03 12:37:59.039 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
09-03 12:37:59.039 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-03 12:37:59.049 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
09-03 12:37:59.049 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
09-03 12:37:59.059 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-03 12:37:59.059 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-03 12:37:59.059 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err:     at java.lang.Thread.run(Thread.java:841)

机型为：华为荣耀G620S-UL100
系统为：andriod 4.4.4

**Comment by froyomu** [comment]
将sql语句中的0x01 替换成MessageStatus.LOCAL_STATUS_PROCESSION，like this，"SELECT a.'From', GROUP_CONCAT(a.MsgId) as msgIdList  FROM IM_Message as a WHERE (" + MessageStatus.LOCAL_STATUS_PROCESSION + " & a.ReadedTag)<>" + MessageStatus.LOCAL_STATUS_PROCESSION + " and a.'From' <> ? GROUP By a.'From';";

**Comment by froyomu** [comment]
> 09-03 12:37:58.989 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err: android.database.sqlite.SQLiteException: unrecognized token: "0x01" (Sqlite code 1): , while compiling: SELECT a.'From', GROUP_CONCAT(a.MsgId) as msgIdList FROM IM_Message as a WHERE (0x01 & a.ReadedTag)<>0x01 and a.'From' <> ? GROUP By a.'From';, (OS error - 2:No such file or directory)
> 09-03 12:37:59.009 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err: at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
> 09-03 12:37:59.009 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err: at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
> 09-03 12:37:59.009 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err: at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
> 09-03 12:37:59.019 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err: at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
> 09-03 12:37:59.019 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err: at android.database.sqlite.SQLiteProgram.(SQLiteProgram.java:58)
> 09-03 12:37:59.019 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err: at android.database.sqlite.SQLiteQuery.(SQLiteQuery.java:37)
> 09-03 12:37:59.029 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err: at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
> 09-03 12:37:59.029 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err: at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
> 09-03 12:37:59.029 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err: at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1253)
> 09-03 12:37:59.029 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err: at com.qunar.im.core.manager.IMDatabaseManager.getMessageStateSendNotXmppIdJson(IMDatabaseManager.java:6188)
> 09-03 12:37:59.029 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err: at com.qunar.im.core.manager.LoginComplateManager.updateMessageStateNoticeServer(LoginComplateManager.java:292)
> 09-03 12:37:59.039 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err: at com.qunar.im.core.manager.LoginComplateManager.loginComplate(LoginComplateManager.java:115)
> 09-03 12:37:59.039 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err: at com.qunar.im.core.manager.IMLogicManager$7.run(IMLogicManager.java:1702)
> 09-03 12:37:59.039 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
> 09-03 12:37:59.039 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err: at java.util.concurrent.FutureTask.run(FutureTask.java:237)
> 09-03 12:37:59.049 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
> 09-03 12:37:59.049 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
> 09-03 12:37:59.059 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
> 09-03 12:37:59.059 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
> 09-03 12:37:59.059 887-1203/sdk.im.qunar.com.qtalksdkdemo W/System.err: at java.lang.Thread.run(Thread.java:841)
> 
> 机型为：华为荣耀G620S-UL100
> 系统为：andriod 4.4.4

将sql语句中的0x01 替换成MessageStatus.LOCAL_STATUS_PROCESSION，like this，"SELECT a.'From', GROUP_CONCAT(a.MsgId) as msgIdList FROM IM_Message as a WHERE (" + MessageStatus.LOCAL_STATUS_PROCESSION + " & a.ReadedTag)<>" + MessageStatus.LOCAL_STATUS_PROCESSION + " and a.'From' <> ? GROUP By a.'From';";

**Comment by froyomu** [comment]
没依赖源码工程module的话，可以清除一下本地的依赖缓存，重新sync project
